systemd_override_dir: /etc/systemd/system

database_name: sonar
database_username: sonar
database_password: sonarsonar

sonar_mysql_username: "{{ database_name }}"
sonar_mysql_password: "{{ database_username }}"
sonar_mysql_database: "{{ database_password }}"

date:
  month: "{{ ansible_date_time.month }}"
  day: "{{ ansible_date_time.day }}"
  year: "{{ ansible_date_time.year }}"

mysql_databases:
  - name: "{{ database_name }}"
    encoding: latin1
    collation: latin1_general_ci

mysql_users:
  - name: "{{ database_username }}"
    host: "%"
    password: "{{ database_password }}"
    priv: "sonar.*:ALL"

sonar_mysql_allowed_hosts:
  - 127.0.0.1
  - ::1
  - localhost
