#!/bin/bash

# Run me with sudo.

apt-get install -y python-dev libssl-dev libffi-dev libxml2-dev libxslt-dev python-pip
pip --upgrade install -r requirements.txt
export ANSIBLE_HOST_KEY_CHECKING=False
